# .streamlit/config.toml
[theme]
primaryColor = "#4e8cff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[server]
port = 8501
enableCORS = false
